import { useEffect, useRef, useState, useMemo } from 'react';
import type { PhDThesisTopic } from '../types/phd-thesis';
import { autoGeneratedThesisTopics } from '../data/auto-generated-thesis-topics';

// College colors matching the credential system
const collegeColors: Record<string, string> = {
  'HUM': '#8B4513',    // Brown
  'MATH': '#1E88E5',   // Blue
  'NAT': '#43A047',    // Green
  'AINS': '#7B1FA2',   // Purple
  'SOC': '#E53935',    // Red
  'ELA': '#F57C00',    // Orange
  'ARTS': '#E91E63',   // Pink
  'HEAL': '#00ACC1',   // Cyan
  'CEF': '#558B2F',    // Dark green
  'META': '#5D4037',   // Dark brown
};

const collegeNames: Record<string, string> = {
  'HUM': 'Humanities',
  'MATH': 'Mathematics',
  'NAT': 'Natural Sciences',
  'AINS': 'AI & Computer Science',
  'SOC': 'Social Sciences',
  'ELA': 'Language Arts',
  'ARTS': 'Arts',
  'HEAL': 'Health',
  'CEF': 'Ecology & Environment',
  'META': 'Meta/Learning',
};

interface ThesisVisualizationProps {
  topics?: PhDThesisTopic[];
}

export default function ThesisVisualization({ topics = autoGeneratedThesisTopics }: ThesisVisualizationProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [selectedThesis, setSelectedThesis] = useState<PhDThesisTopic | null>(null);
  const [filter, setFilter] = useState<'all' | 'cross' | 'single'>('all');
  const [minColleges, setMinColleges] = useState(2);

  // Analyze cross-disciplinary theses
  const analysis = useMemo(() => {
    const crossDisciplinary: Array<{ topic: PhDThesisTopic; colleges: string[]; numColleges: number }> = [];
    const singleDiscipline: PhDThesisTopic[] = [];

    const topicToColleges = (topicName: string): string[] => {
      const topicLower = topicName.toLowerCase();
      const colleges: string[] = [];
      
      if (topicLower.includes('computer') || topicLower.includes('artificial intelligence') || 
          topicLower.includes('machine learning') || topicLower.includes('neural network') || 
          topicLower.includes('algorithm') || topicLower.includes('software')) {
        colleges.push('AINS');
      }
      if (topicLower.includes('mathematics') || topicLower.includes('mathematical') || 
          topicLower.includes('statistics') || topicLower.includes('algebra') || 
          topicLower.includes('geometry') || topicLower.includes('optimization')) {
        colleges.push('MATH');
      }
      if (topicLower.includes('physics') || topicLower.includes('quantum') || 
          topicLower.includes('mechanics') || topicLower.includes('thermodynamics')) {
        colleges.push('NAT');
      }
      if (topicLower.includes('chemistry') || topicLower.includes('chemical') || 
          topicLower.includes('molecular') || topicLower.includes('organic')) {
        colleges.push('NAT');
      }
      if (topicLower.includes('biology') || topicLower.includes('biological') || 
          topicLower.includes('genetics') || topicLower.includes('evolution')) {
        colleges.push('NAT');
      }
      if (topicLower.includes('linguistics') || topicLower.includes('language') || 
          topicLower.includes('syntax') || topicLower.includes('phonology') || 
          topicLower.includes('semantics') || topicLower.includes('speech')) {
        colleges.push('ELA');
      }
      if (topicLower.includes('philosophy') || topicLower.includes('philosophical') || 
          topicLower.includes('ethics')) {
        colleges.push('HUM');
      }
      if (topicLower.includes('literature') || topicLower.includes('literary') || 
          topicLower.includes('narrative') || topicLower.includes('text')) {
        colleges.push('ELA');
      }
      if (topicLower.includes('history') || topicLower.includes('historical')) {
        colleges.push('HUM');
      }
      if (topicLower.includes('psychology') || topicLower.includes('psychological') || 
          topicLower.includes('cognitive')) {
        colleges.push('SOC');
      }
      if (topicLower.includes('sociology') || topicLower.includes('social') || 
          topicLower.includes('society')) {
        colleges.push('SOC');
      }
      if (topicLower.includes('economics') || topicLower.includes('economic') || 
          topicLower.includes('market')) {
        colleges.push('SOC');
      }
      if (topicLower.includes('medicine') || topicLower.includes('medical') || 
          topicLower.includes('health') || topicLower.includes('clinical')) {
        colleges.push('HEAL');
      }
      if (topicLower.includes('art') || topicLower.includes('music') || 
          topicLower.includes('aesthetic') || topicLower.includes('visual') || 
          topicLower.includes('audio')) {
        colleges.push('ARTS');
      }
      if (topicLower.includes('ecology') || topicLower.includes('environment') || 
          topicLower.includes('sustainability') || topicLower.includes('climate')) {
        colleges.push('CEF');
      }
      if (topicLower.includes('education') || topicLower.includes('pedagogy') || 
          topicLower.includes('learning') || topicLower.includes('teaching')) {
        colleges.push('META');
      }
      
      return colleges.length > 0 ? colleges : ['META'];
    };

    topics.forEach(topic => {
      const primaryCollege = topic.college_primary || 'META';
      const openalexTopics = topic.openalex_topics || [];
      const topicColleges = new Set<string>();
      
      openalexTopics.forEach(t => {
        const topicName = t.display_name || '';
        topicToColleges(topicName).forEach(c => topicColleges.add(c));
      });
      
      topic.keywords?.forEach(kw => {
        topicToColleges(kw).forEach(c => topicColleges.add(c));
      });
      
      topicColleges.add(primaryCollege);
      
      const allColleges = Array.from(topicColleges);
      
      if (allColleges.length > 1) {
        crossDisciplinary.push({
          topic,
          colleges: allColleges,
          numColleges: allColleges.length,
        });
      } else {
        singleDiscipline.push(topic);
      }
    });

    return { crossDisciplinary, singleDiscipline };
  }, [topics]);

  const filteredTopics = useMemo(() => {
    if (filter === 'cross') {
      return analysis.crossDisciplinary
        .filter(item => item.numColleges >= minColleges)
        .map(item => item.topic);
    } else if (filter === 'single') {
      return analysis.singleDiscipline;
    }
    return topics;
  }, [filter, minColleges, analysis, topics]);

  // Draw network visualization
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Set canvas size
    const dpr = window.devicePixelRatio || 1;
    const rect = canvas.getBoundingClientRect();
    canvas.width = rect.width * dpr;
    canvas.height = rect.height * dpr;
    ctx.scale(dpr, dpr);
    canvas.style.width = rect.width + 'px';
    canvas.style.height = rect.height + 'px';

    ctx.clearRect(0, 0, canvas.width, canvas.height);

    // Draw college nodes in a circle
    const centerX = rect.width / 2;
    const centerY = rect.height / 2;
    const radius = Math.min(rect.width, rect.height) * 0.3;
    const colleges = Object.keys(collegeColors);
    const angleStep = (2 * Math.PI) / colleges.length;

    // Draw connections
    ctx.strokeStyle = 'rgba(0, 0, 0, 0.1)';
    ctx.lineWidth = 1;

    analysis.crossDisciplinary
      .filter(item => item.numColleges >= minColleges)
      .forEach(item => {
        const collegeIndices = item.colleges.map(c => colleges.indexOf(c)).filter(i => i >= 0);
        if (collegeIndices.length < 2) return;

        // Draw connections between colleges
        for (let i = 0; i < collegeIndices.length; i++) {
          for (let j = i + 1; j < collegeIndices.length; j++) {
            const idx1 = collegeIndices[i];
            const idx2 = collegeIndices[j];
            const angle1 = idx1 * angleStep - Math.PI / 2;
            const angle2 = idx2 * angleStep - Math.PI / 2;
            const x1 = centerX + radius * Math.cos(angle1);
            const y1 = centerY + radius * Math.sin(angle1);
            const x2 = centerX + radius * Math.cos(angle2);
            const y2 = centerY + radius * Math.sin(angle2);

            ctx.beginPath();
            ctx.moveTo(x1, y1);
            ctx.lineTo(x2, y2);
            ctx.stroke();
          }
        }
      });

    // Draw college nodes
    colleges.forEach((college, idx) => {
      const angle = idx * angleStep - Math.PI / 2;
      const x = centerX + radius * Math.cos(angle);
      const y = centerY + radius * Math.sin(angle);

      // Count connections
      const count = analysis.crossDisciplinary.filter(item => 
        item.colleges.includes(college) && item.numColleges >= minColleges
      ).length;

      // Draw node
      ctx.fillStyle = collegeColors[college];
      ctx.beginPath();
      ctx.arc(x, y, 15 + Math.sqrt(count) * 2, 0, 2 * Math.PI);
      ctx.fill();

      // Draw label
      ctx.fillStyle = '#333';
      ctx.font = '12px sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(college, x, y + 30);
      ctx.fillText(count.toString(), x, y - 20);
    });

  }, [analysis, minColleges]);

  const stats = {
    total: topics.length,
    cross: analysis.crossDisciplinary.length,
    single: analysis.singleDiscipline.length,
    crossPct: (analysis.crossDisciplinary.length / topics.length * 100).toFixed(1),
  };

  return (
    <div style={{ padding: '2rem', fontFamily: 'system-ui, sans-serif' }}>
      <h1>PhD Thesis Cross-Disciplinary Analysis</h1>
      
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '2rem', marginTop: '2rem' }}>
        {/* Controls and Stats */}
        <div>
          <div style={{ background: 'white', padding: '1.5rem', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }}>
            <h2>Statistics</h2>
            <div style={{ marginTop: '1rem' }}>
              <div style={{ marginBottom: '0.5rem' }}>
                <strong>Total Theses:</strong> {stats.total.toLocaleString()}
              </div>
              <div style={{ marginBottom: '0.5rem', color: '#7B1FA2' }}>
                <strong>Cross-Disciplinary:</strong> {stats.cross.toLocaleString()} ({stats.crossPct}%)
              </div>
              <div style={{ marginBottom: '0.5rem', color: '#666' }}>
                <strong>Single Discipline:</strong> {stats.single.toLocaleString()}
              </div>
            </div>

            <div style={{ marginTop: '1.5rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem' }}>
                <strong>Filter:</strong>
              </label>
              <select 
                value={filter} 
                onChange={(e) => setFilter(e.target.value as any)}
                style={{ width: '100%', padding: '0.5rem', fontSize: '1rem' }}
              >
                <option value="all">All Theses</option>
                <option value="cross">Cross-Disciplinary Only</option>
                <option value="single">Single Discipline Only</option>
              </select>
            </div>

            <div style={{ marginTop: '1rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem' }}>
                <strong>Minimum Colleges:</strong> {minColleges}
              </label>
              <input
                type="range"
                min="2"
                max="6"
                value={minColleges}
                onChange={(e) => setMinColleges(Number(e.target.value))}
                style={{ width: '100%' }}
              />
            </div>

            <div style={{ marginTop: '1.5rem', fontSize: '0.9rem', color: '#666' }}>
              <strong>College Legend:</strong>
              <div style={{ marginTop: '0.5rem', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.25rem' }}>
                {Object.entries(collegeColors).map(([code, color]) => (
                  <div key={code} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <div style={{ width: '12px', height: '12px', background: color, borderRadius: '2px' }}></div>
                    <span>{code}: {collegeNames[code]}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Top Combinations */}
          <div style={{ background: 'white', padding: '1.5rem', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)', marginTop: '1rem' }}>
            <h3>Top College Combinations</h3>
            <div style={{ marginTop: '0.5rem', fontSize: '0.9rem' }}>
              {Array.from(
                new Map(
                  analysis.crossDisciplinary
                    .filter(item => item.numColleges >= minColleges)
                    .map(item => [item.colleges.sort().join(' + '), item.colleges])
                    .map(([key, colleges]) => [key, { colleges, count: 0 }])
                ).entries()
              )
                .map(([key, data]) => {
                  const count = analysis.crossDisciplinary.filter(item => 
                    item.colleges.sort().join(' + ') === key && item.numColleges >= minColleges
                  ).length;
                  return { key, count, colleges: data.colleges };
                })
                .sort((a, b) => b.count - a.count)
                .slice(0, 10)
                .map((item, idx) => (
                  <div key={idx} style={{ marginBottom: '0.5rem', padding: '0.5rem', background: '#f5f5f5', borderRadius: '4px' }}>
                    <div style={{ fontWeight: 'bold' }}>{item.key}</div>
                    <div style={{ fontSize: '0.85rem', color: '#666' }}>{item.count} theses</div>
                  </div>
                ))}
            </div>
          </div>
        </div>

        {/* Visualization */}
        <div>
          <div style={{ background: 'white', padding: '1.5rem', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)' }}>
            <h2>College Network Visualization</h2>
            <p style={{ color: '#666', fontSize: '0.9rem', marginTop: '0.5rem' }}>
              Connections show cross-disciplinary theses. Node size indicates number of connections.
            </p>
            <canvas
              ref={canvasRef}
              style={{ width: '100%', height: '600px', border: '1px solid #e0e0e0', borderRadius: '4px', marginTop: '1rem' }}
            />
          </div>

          {/* Selected Thesis Details */}
          {selectedThesis && (
            <div style={{ background: 'white', padding: '1.5rem', borderRadius: '8px', boxShadow: '0 2px 8px rgba(0,0,0,0.1)', marginTop: '1rem' }}>
              <h3>{selectedThesis.title}</h3>
              <div style={{ marginTop: '0.5rem', fontSize: '0.9rem', color: '#666' }}>
                {selectedThesis.author && <div>Author: {selectedThesis.author}</div>}
                {selectedThesis.year && <div>Year: {selectedThesis.year}</div>}
                {selectedThesis.college_primary && (
                  <div>Primary College: <span style={{ color: collegeColors[selectedThesis.college_primary] }}>
                    {selectedThesis.college_primary}
                  </span></div>
                )}
              </div>
              <button 
                onClick={() => setSelectedThesis(null)}
                style={{ marginTop: '1rem', padding: '0.5rem 1rem', background: '#7B1FA2', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}
              >
                Close
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
